"""thread can't have duplicated users

Revision ID: 764d479f2c2f
Revises: e7af119200f8
Create Date: 2024-07-13 21:46:48.515845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "764d479f2c2f"
down_revision: Union[str, None] = "e7af119200f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("twitter_object_thread_id_key", "twitter_object", type_="unique")
    op.drop_constraint(
        "twitter_object_twitter_username_key", "twitter_object", type_="unique"
    )
    op.create_unique_constraint(
        "thread_username", "twitter_object", ["thread_id", "twitter_username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("thread_username", "twitter_object", type_="unique")
    op.create_unique_constraint(
        "twitter_object_twitter_username_key", "twitter_object", ["twitter_username"]
    )
    op.create_unique_constraint(
        "twitter_object_thread_id_key", "twitter_object", ["thread_id"]
    )
    # ### end Alembic commands ###
